[package]
name = "school-calander"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.28"
icalendar = "0.15.7"
rocket = { version="0.5.0-rc.2" }
serde = "1.0.188"
serde_json = "1.0.105"
